/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Toolkit;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabela;
import modeloConnection.conexaoBD;
import modeloDao.DaouUsuario;

/**
 *
 * @author rafa
 */
public class FormUsuario extends javax.swing.JFrame {
    BeansUsuario mod = new BeansUsuario();
    DaouUsuario dao = new DaouUsuario();
    conexaoBD conex = new conexaoBD();
    int flag=0;

    public FormUsuario() {
        initComponents();
        preencherTabela("select *from usuarios order by usu_nome");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeUser = new javax.swing.JTextField();
        jComboBoxUser = new javax.swing.JComboBox<>();
        jPasswordFieldUser = new javax.swing.JPasswordField();
        jPasswordFieldUser2 = new javax.swing.JPasswordField();
        jButtonNovoUser = new javax.swing.JButton();
        jButtonSalvarUser = new javax.swing.JButton();
        jButtonCancelarUser = new javax.swing.JButton();
        jButtonEditarUser = new javax.swing.JButton();
        jButtonExcluirUser = new javax.swing.JButton();
        jTextFieldPesquisaUser = new javax.swing.JTextField();
        jButtonPesquisarUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jButtonAddImageUser = new javax.swing.JButton();
        jLabelImageUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Sistema_Mais_Saude/icone3.png"));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Usuários", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 80, 60, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 130, 50, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Tipo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 80, 40, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Confirmar Senha");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 130, 130, 30);

        jTextFieldNomeUser.setEnabled(false);
        jPanel1.add(jTextFieldNomeUser);
        jTextFieldNomeUser.setBounds(220, 80, 240, 30);
        jTextFieldNomeUser.getAccessibleContext().setAccessibleName("");

        jComboBoxUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Médico", "Recepcionista" }));
        jComboBoxUser.setSelectedItem(null);
        jComboBoxUser.setEnabled(false);
        jPanel1.add(jComboBoxUser);
        jComboBoxUser.setBounds(520, 80, 120, 30);
        jComboBoxUser.getAccessibleContext().setAccessibleName("");

        jPasswordFieldUser.setEnabled(false);
        jPanel1.add(jPasswordFieldUser);
        jPasswordFieldUser.setBounds(220, 130, 150, 30);
        jPasswordFieldUser.getAccessibleContext().setAccessibleName("");

        jPasswordFieldUser2.setEnabled(false);
        jPanel1.add(jPasswordFieldUser2);
        jPasswordFieldUser2.setBounds(520, 130, 150, 30);
        jPasswordFieldUser2.getAccessibleContext().setAccessibleName("");

        jButtonNovoUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovoUser.setText("Novo");
        jButtonNovoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovoUser);
        jButtonNovoUser.setBounds(30, 200, 90, 35);
        jButtonNovoUser.getAccessibleContext().setAccessibleName("");

        jButtonSalvarUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvarUser.setText("Salvar");
        jButtonSalvarUser.setEnabled(false);
        jButtonSalvarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvarUser);
        jButtonSalvarUser.setBounds(30, 240, 90, 35);
        jButtonSalvarUser.getAccessibleContext().setAccessibleName("");

        jButtonCancelarUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelarUser.setText("Cancelar");
        jButtonCancelarUser.setEnabled(false);
        jButtonCancelarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelarUser);
        jButtonCancelarUser.setBounds(30, 280, 90, 35);
        jButtonCancelarUser.getAccessibleContext().setAccessibleName("");

        jButtonEditarUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditarUser.setText("Editar");
        jButtonEditarUser.setEnabled(false);
        jButtonEditarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarUser);
        jButtonEditarUser.setBounds(30, 320, 90, 35);
        jButtonEditarUser.getAccessibleContext().setAccessibleName("");

        jButtonExcluirUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirUser.setText("Excluir");
        jButtonExcluirUser.setEnabled(false);
        jButtonExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluirUser);
        jButtonExcluirUser.setBounds(30, 360, 90, 35);
        jButtonExcluirUser.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jTextFieldPesquisaUser);
        jTextFieldPesquisaUser.setBounds(210, 200, 240, 30);

        jButtonPesquisarUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisarUser.setText("Pesquisar");
        jButtonPesquisarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisarUser);
        jButtonPesquisarUser.setBounds(460, 200, 100, 33);

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUser);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(210, 240, 350, 150);

        jButtonAddImageUser.setToolTipText("Click para Add Foto");
        jButtonAddImageUser.setBorderPainted(false);
        jButtonAddImageUser.setContentAreaFilled(false);
        jButtonAddImageUser.setEnabled(false);
        jButtonAddImageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddImageUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddImageUser);
        jButtonAddImageUser.setBounds(20, 30, 120, 130);

        jLabelImageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile_icon.png"))); // NOI18N
        jLabelImageUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelImageUser);
        jLabelImageUser.setBounds(20, 30, 120, 130);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 40, 20, 30);

        jTextFieldCod.setEnabled(false);
        jPanel1.add(jTextFieldCod);
        jTextFieldCod.setBounds(220, 40, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 690, 430);

        setSize(new java.awt.Dimension(719, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUserActionPerformed
        flag=1;
        jTextFieldNomeUser.setEnabled(true);
        jComboBoxUser.setEnabled(true);
        jPasswordFieldUser.setEnabled(true);
        jPasswordFieldUser2.setEnabled(true);
        jButtonSalvarUser.setEnabled(true);
        jButtonCancelarUser.setEnabled(true);
        jTextFieldPesquisaUser.setEnabled(false);
        jButtonPesquisarUser.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoUserActionPerformed

    private void jButtonAddImageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddImageUserActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
            int opt = arquivo.showOpenDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION){
                File file = new File("Caminho");
                file = arquivo.getSelectedFile(); //Recebe O Caminho.
                
                ImageIcon imagem = new ImageIcon(arquivo.getSelectedFile().getPath());
                jLabelImageUser.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLabelImageUser.getWidth(),jLabelImageUser.getHeight(), Image.SCALE_DEFAULT)));
            }
    }//GEN-LAST:event_jButtonAddImageUserActionPerformed

    private void jButtonSalvarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarUserActionPerformed
        if (jTextFieldNomeUser.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o Campo Nome para Continuar!");
          jTextFieldNomeUser.requestFocus();
      }else if(jPasswordFieldUser.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"Preencha o Campo Senha para Continuar!");
          jPasswordFieldUser.requestFocus();
      }else if (jPasswordFieldUser2.getText().isEmpty()){ 
          JOptionPane.showMessageDialog(null,"Preencha o Campo Confirmar Senha para Continuar!");
          jPasswordFieldUser2.requestFocus();
        
      
      }else    
          
          
        if(flag==1){
          
      mod.setUsuNOME(jTextFieldNomeUser.getText());
      mod.setUsuTipo((String) jComboBoxUser.getSelectedItem());
      mod.setUsuSenha(jPasswordFieldUser.getText());
      dao.Salvar(mod);
      jTextFieldNomeUser.setText("");
      jPasswordFieldUser.setText("");
      jPasswordFieldUser2.setText("");
      jComboBoxUser.setSelectedItem(null);
      jTextFieldNomeUser.setEnabled(false);
      jPasswordFieldUser.setEnabled(false);
      jPasswordFieldUser2.setEnabled(false);
      jComboBoxUser.setEnabled(false);
      jButtonSalvarUser.setEnabled(false);
      jButtonCancelarUser.setEnabled(false);
       preencherTabela("select *from usuarios order by usu_nome");
       
       }else{
      mod.setUsuCod(Integer.parseInt(jTextFieldCod.getText()));
      mod.setUsuNOME(jTextFieldNomeUser.getText());
      mod.setUsuTipo((String) jComboBoxUser.getSelectedItem());
      mod.setUsuSenha(jPasswordFieldUser.getText());
      dao.Alterar(mod);
      jTextFieldCod.setText("");
      jTextFieldNomeUser.setText("");
      jPasswordFieldUser.setText(""); 
      jPasswordFieldUser2.setText("");
      jComboBoxUser.setSelectedItem(null);
      jTextFieldNomeUser.setEnabled(false);
      jPasswordFieldUser.setEnabled(false);
      jPasswordFieldUser2.setEnabled(false);
      jComboBoxUser.setEnabled(false);
      jButtonSalvarUser.setEnabled(false);  
      jButtonNovoUser.setEnabled(true);
      jButtonCancelarUser.setEnabled(false);
      preencherTabela("select *from usuarios order by usu_nome");
    }                                             
    
    }
    private void jLabeImageComponentAdded(java.awt.event.ContainerEvent evt) {                                          

    }                                         

    private void jFormattedTextFieldCRMActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void jButtonAddImageActionPerformed(java.awt.event.ActionEvent evt) {                                                
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
            int opt = arquivo.showOpenDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION){
                File file = new File("Caminho");
                file = arquivo.getSelectedFile(); //Recebe O Caminho.
                
                ImageIcon imagem = new ImageIcon(arquivo.getSelectedFile().getPath());
                jLabelImageUser.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLabelImageUser.getWidth(),jLabelImageUser.getHeight(), Image.SCALE_DEFAULT)));
                
                
            }
    }//GEN-LAST:event_jButtonSalvarUserActionPerformed

    private void jButtonPesquisarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarUserActionPerformed
         mod.setUsuPesquisar(jTextFieldPesquisaUser.getText());// Atributo pesquisa insere dentro do método de pesquisa o que o usuário digitou.
        BeansUsuario model = dao.buscaUsuario(mod);// Chama o método buscaMedico.
        /*Função que envia o modelo (setPesquisa) e chamando o método (buscaMedico) enviando
        *por parâmetro (mod) o que o usuário digitou. 
        */
       jTextFieldCod.setText(String.valueOf(model.getUsuCod()));
        jTextFieldNomeUser.setText(model.getUsuNOME());
        jPasswordFieldUser.setText(model.getUsuSenha());
        jPasswordFieldUser2.setText(model.getUsuSenha());
         jComboBoxUser.setSelectedItem(model.getUsuTipo());
         jButtonEditarUser.setEnabled(true);
         jButtonExcluirUser.setEnabled(true);
         preencherTabela("select *from usuarios order by usu_nome");
    }//GEN-LAST:event_jButtonPesquisarUserActionPerformed

    private void jButtonEditarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUserActionPerformed
       flag=2;
        jTextFieldNomeUser.setEnabled(true);
        jComboBoxUser.setEnabled(true);
        jPasswordFieldUser.setEnabled(true);
        jPasswordFieldUser2.setEnabled(true);
        jButtonSalvarUser.setEnabled(true);
        jButtonNovoUser.setEnabled(false);
        jButtonCancelarUser.setEnabled(true);
        jButtonExcluirUser.setEnabled(false);
        jButtonEditarUser.setEnabled(false);
        preencherTabela("select *from usuarios order by usu_nome");
       
    }//GEN-LAST:event_jButtonEditarUserActionPerformed

    private void jButtonExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirUserActionPerformed
      int resposta =0;
        resposta =JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir o Usuário?");
        if(resposta==JOptionPane.YES_OPTION){
        mod.setUsuCod(Integer.parseInt(jTextFieldCod.getText()));
        dao.Excluir(mod);
        jTextFieldNomeUser.setText("");
          jPasswordFieldUser.setText(""); 
          jPasswordFieldUser2.setText("");
          jTextFieldCod.setText("");
          jComboBoxUser.setSelectedItem(null);
          jTextFieldNomeUser.setEnabled(false);
          jPasswordFieldUser.setEnabled(false);
          jPasswordFieldUser2.setEnabled(false);
          jComboBoxUser.setEnabled(false);
          jButtonSalvarUser.setEnabled(false);  
          jButtonNovoUser.setEnabled(true);
          jButtonCancelarUser.setEnabled(false);
          jButtonEditarUser.setEnabled(false);
          jButtonExcluirUser.setEnabled(false);
        
        preencherTabela("select *from usuarios order by usu_nome");
    }//GEN-LAST:event_jButtonExcluirUserActionPerformed
    }
    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
         String usu_nome=""+jTableUser.getValueAt(jTableUser.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select *from usuarios where usu_nome='"+usu_nome+"'");
        try {
            conex.rs.first();
            jTextFieldCod.setText(String.valueOf(conex.rs.getInt("usu_cod")));
            jTextFieldNomeUser.setText(conex.rs.getString("usu_nome"));
            jComboBoxUser.setSelectedItem(conex.rs.getString("usu_tipo"));
            jButtonEditarUser.setEnabled(true);
            jButtonExcluirUser.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar os Dados!\n"+ex.getMessage());
            
        }
        conex.desconecta();
    }//GEN-LAST:event_jTableUserMouseClicked

    private void jButtonCancelarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarUserActionPerformed
     jTextFieldNomeUser.setEnabled(!true);
      jPasswordFieldUser.setEnabled(!true);
      jComboBoxUser.setEnabled(!true);
      jButtonSalvarUser.setEnabled(!true);
       jLabelImageUser.setEnabled(!true);
        jButtonAddImageUser.setEnabled(!true);
        jButtonCancelarUser.setEnabled(!true);
        jButtonNovoUser.setEnabled(true);
        jButtonEditarUser.setEnabled(false);
        jButtonExcluirUser.setEnabled(false);
        jTextFieldPesquisaUser.setEnabled(true);
        jButtonPesquisarUser.setEnabled(true);
        jPasswordFieldUser2.setEnabled(false);
        jTextFieldCod.setText("");
         jTextFieldNomeUser.setText("");
         jPasswordFieldUser.setText(""); 
         jPasswordFieldUser2.setText("");
         jComboBoxUser.setSelectedItem(null);
    }//GEN-LAST:event_jButtonCancelarUserActionPerformed
    
     public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Usuário", "Tipo"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
        
            do{
                dados.add(new Object[]{conex.rs.getInt("usu_cod"), conex.rs.getString("usu_nome"),conex.rs.getString("usu_tipo")});
            }while(conex.rs.next());//Enquanto houver dados ele vai percorrer o registro.
        }catch (SQLException ex){
            //SJOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList\n"+ex.getMessage());   
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {};
        
        jTableUser.setModel(modelo);
        jTableUser.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTableUser.getColumnModel().getColumn(0).setResizable(false);
        jTableUser.getColumnModel().getColumn(1).setPreferredWidth(210);
        jTableUser.getColumnModel().getColumn(1).setResizable(false);
        jTableUser.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableUser.getColumnModel().getColumn(2).setResizable(false);
        jTableUser.getTableHeader().setReorderingAllowed(false);
        jTableUser.setAutoResizeMode(jTableUser.AUTO_RESIZE_OFF);// Bloqueia Tabela para redimensionamento.
        jTableUser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);// Usuário só pode selecionar um campo da tabela por vez.
        conex.desconecta();
    }
    

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddImageUser;
    private javax.swing.JButton jButtonCancelarUser;
    private javax.swing.JButton jButtonEditarUser;
    private javax.swing.JButton jButtonExcluirUser;
    private javax.swing.JButton jButtonNovoUser;
    private javax.swing.JButton jButtonPesquisarUser;
    private javax.swing.JButton jButtonSalvarUser;
    private javax.swing.JComboBox<String> jComboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelImageUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldUser;
    private javax.swing.JPasswordField jPasswordFieldUser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNomeUser;
    private javax.swing.JTextField jTextFieldPesquisaUser;
    // End of variables declaration//GEN-END:variables
}
