/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modeloBeans.BeansPaciente;
import modeloBeans.ModeloTabela;
import modeloConnection.conexaoBD;
import modeloDao.DaoPacientes;


public final class FormPaciente extends javax.swing.JFrame {
   
   BeansPaciente mod = new BeansPaciente();
    DaoPacientes control = new DaoPacientes();
    conexaoBD conex = new conexaoBD();
    int flag = 0;
    
    
    public FormPaciente() {
        initComponents();
         preencherTabela("select *from pacientes order by nome_paci");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomePaciente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jFormattedTextFieldNascimentoPaciente = new javax.swing.JFormattedTextField();
        jButtonAddImagePaciente = new javax.swing.JButton();
        jLabelImagePaciente = new javax.swing.JLabel();
        jFormattedTextFieldRG = new javax.swing.JTextField();
        jTextFieldSUS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadstro de Pacientes");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Sistema_Mais_Saude/icone3.png"));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Pacientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 57, 50, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("RG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 97, 30, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nascimento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 50, 90, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("SUS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 90, 40, 30);

        jTextFieldNomePaciente.setEnabled(false);
        jTextFieldNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNomePaciente);
        jTextFieldNomePaciente.setBounds(220, 50, 220, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Rua");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 32, 29, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("nº");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(270, 30, 20, 30);

        jTextFieldRua.setEnabled(false);
        jPanel2.add(jTextFieldRua);
        jTextFieldRua.setBounds(70, 30, 190, 30);

        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNumero);
        jTextFieldNumero.setBounds(290, 30, 50, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Bairro");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 82, 45, 30);

        jTextFieldBairro.setEnabled(false);
        jPanel2.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(70, 80, 130, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("CEP");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(350, 30, 40, 30);

        jTextFieldCep.setEnabled(false);
        jTextFieldCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCepActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCep);
        jTextFieldCep.setBounds(390, 30, 120, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Telefone");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(260, 80, 70, 30);

        jTextFieldTel.setEnabled(false);
        jPanel2.add(jTextFieldTel);
        jTextFieldTel.setBounds(330, 80, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(160, 140, 540, 140);

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 330, 540, 160);
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(160, 290, 180, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(350, 290, 100, 33);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(30, 200, 90, 35);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(30, 240, 90, 35);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(30, 280, 90, 35);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(30, 320, 90, 35);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(30, 360, 90, 35);

        jFormattedTextFieldNascimentoPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedTextFieldNascimentoPaciente.setEnabled(false);
        jFormattedTextFieldNascimentoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNascimentoPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldNascimentoPaciente);
        jFormattedTextFieldNascimentoPaciente.setBounds(550, 50, 110, 30);

        jButtonAddImagePaciente.setBorder(null);
        jButtonAddImagePaciente.setContentAreaFilled(false);
        jButtonAddImagePaciente.setEnabled(false);
        jButtonAddImagePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddImagePacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddImagePaciente);
        jButtonAddImagePaciente.setBounds(20, 40, 120, 130);

        jLabelImagePaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagePaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile_icon.png"))); // NOI18N
        jLabelImagePaciente.setToolTipText("Click para Add Imagem");
        jLabelImagePaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelImagePaciente);
        jLabelImagePaciente.setBounds(20, 40, 120, 130);

        jFormattedTextFieldRG.setEnabled(false);
        jPanel1.add(jFormattedTextFieldRG);
        jFormattedTextFieldRG.setBounds(220, 90, 140, 30);

        jTextFieldSUS.setEnabled(false);
        jPanel1.add(jTextFieldSUS);
        jTextFieldSUS.setBounds(480, 90, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 740, 520);

        setSize(new java.awt.Dimension(779, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePacienteActionPerformed

    private void jTextFieldCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCepActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
      flag=2;
     jTextFieldNomePaciente.setEnabled(true);
      jFormattedTextFieldNascimentoPaciente.setEnabled(true);
      jTextFieldSUS.setEnabled(true);
      jFormattedTextFieldRG.setEnabled(true);
      jTextFieldRua.setEnabled(true);
      jTextFieldNumero.setEnabled(true);
      jTextFieldCep.setEnabled(true);
      jTextFieldBairro.setEnabled(true);
      jTextFieldTel.setEnabled(true);
      jButtonSalvar.setEnabled(true);
       jLabelImagePaciente.setEnabled(true);
        jButtonAddImagePaciente.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("select * from pacientes order by nome_paci");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jFormattedTextFieldNascimentoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNascimentoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNascimentoPacienteActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jButtonAddImagePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddImagePacienteActionPerformed
      JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
            int opt = arquivo.showOpenDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION){
                File file = new File("Caminho");
                file = arquivo.getSelectedFile(); //Recebe O Caminho.
                
                ImageIcon imagem = new ImageIcon(arquivo.getSelectedFile().getPath());
                jLabelImagePaciente.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLabelImagePaciente.getWidth(),jLabelImagePaciente.getHeight(), Image.SCALE_DEFAULT)));
                
            }
    }//GEN-LAST:event_jButtonAddImagePacienteActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       flag=1;  
       JFileChooser arquivo = new JFileChooser();
       jTextFieldNomePaciente.setEnabled(true);
      jFormattedTextFieldNascimentoPaciente.setEnabled(true);
      jTextFieldSUS.setEnabled(true);
      jFormattedTextFieldRG.setEnabled(true);
      jTextFieldRua.setEnabled(true);
      jTextFieldNumero.setEnabled(true);
      jTextFieldCep.setEnabled(true);
      jTextFieldBairro.setEnabled(true);
      jTextFieldTel.setEnabled(true);
       jButtonAddImagePaciente.setEnabled(true);
      
      jButtonSalvar.setEnabled(true);
        jButtonAddImagePaciente.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldNomePaciente.setText("");
      jFormattedTextFieldNascimentoPaciente.setText("");
      jTextFieldSUS.setText("");
      jFormattedTextFieldRG.setText("");
      jTextFieldRua.setText("");
      jTextFieldNumero.setText("");
      jTextFieldCep.setText("");
      jTextFieldBairro.setText("");
      jTextFieldTel.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
       jButtonPesquisar.setEnabled(false);
    
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
                                           
      if (jTextFieldNomePaciente.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o Campo Nome para Continuar!");
          jTextFieldNomePaciente.requestFocus();
      }else if(jFormattedTextFieldRG.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"Preencha o Campo RG para Continuar!");
          jFormattedTextFieldNascimentoPaciente.requestFocus();
       }else if(jFormattedTextFieldNascimentoPaciente.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"Preencha o Campo Data de Nascimento para Continuar!");
          jFormattedTextFieldNascimentoPaciente.requestFocus();
       
      }else
      if (flag==1){ 
      mod.setNome(jTextFieldNomePaciente.getText());
      mod.setNascimento(jFormattedTextFieldNascimentoPaciente.getText());
      mod.setRg(Integer.parseInt(jFormattedTextFieldRG.getText()));
      mod.setSus(jTextFieldSUS.getText());
       mod.setRua(jTextFieldRua.getText());
          mod.setBairro(jTextFieldBairro.getText());
          mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
          mod.setCep((jTextFieldCep.getText()));
          mod.setTelefone(jTextFieldTel.getText());
      
      control.Salvar(mod);
      jTextFieldNomePaciente.setText("");
      jFormattedTextFieldNascimentoPaciente.setText("");
      jTextFieldSUS.setText("");
      jFormattedTextFieldRG.setText("");
      jTextFieldRua.setText("");
      jTextFieldBairro.setText("");
      jTextFieldCep.setText("");
      jTextFieldNumero.setText("");
      jTextFieldTel.setText("");
      jTextFieldNomePaciente.setEnabled(false);
      jFormattedTextFieldNascimentoPaciente.setEnabled(false);
      jFormattedTextFieldRG.setEnabled(false);
      jTextFieldSUS.setEnabled(false);
      jTextFieldRua.setEnabled(false);
      jTextFieldNumero.setEnabled(false);
      jTextFieldCep.setEnabled(false);
      jTextFieldBairro.setEnabled(false);
      jTextFieldTel.setEnabled(false);
      jButtonSalvar.setEnabled(false);
      jButtonCancelar.setEnabled(false);
       preencherTabela("select * from pacientes order by nome_paci");
       }else{ 
          mod.setNome(jTextFieldNomePaciente.getText());
      mod.setNascimento(jFormattedTextFieldNascimentoPaciente.getText());
      mod.setRg(Integer.parseInt(jFormattedTextFieldRG.getText()));
      mod.setSus(jTextFieldSUS.getText());
       mod.setRua(jTextFieldRua.getText());
          mod.setBairro(jTextFieldBairro.getText());
          mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
          mod.setCep((jTextFieldCep.getText()));
          mod.setTelefone(jTextFieldTel.getText());
          control.Editar(mod);
          jTextFieldNomePaciente.setText("");
          jFormattedTextFieldNascimentoPaciente.setText("");
          jTextFieldSUS.setText("");
          jFormattedTextFieldRG.setText("");
          jTextFieldRua.setText("");
          jTextFieldBairro.setText("");
          jTextFieldCep.setText("");
          jTextFieldNumero.setText("");
          jTextFieldTel.setText("");

      
      jTextFieldNomePaciente.setEnabled(false);
      jFormattedTextFieldNascimentoPaciente.setEnabled(false);
      jFormattedTextFieldRG.setEnabled(false);
      jTextFieldSUS.setEnabled(false);
      jTextFieldRua.setEnabled(false);
      jTextFieldNumero.setEnabled(false);
      jTextFieldCep.setEnabled(false);
      jTextFieldBairro.setEnabled(false);
      jTextFieldTel.setEnabled(false);
      jButtonSalvar.setEnabled(false);
      jButtonCancelar.setEnabled(false);
          jButtonSalvar.setEnabled(false);  
          jButtonNovo.setEnabled(true);
          jButtonCancelar.setEnabled(false);
           preencherTabela("select * from pacientes order by nome_paci");
          
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       jTextFieldNomePaciente.setEnabled(!true);
      jFormattedTextFieldNascimentoPaciente.setEnabled(!true);
      jFormattedTextFieldRG.setEnabled(!true);
      jTextFieldSUS.setEnabled(!true);
      jTextFieldRua.setEnabled(!true);
       jTextFieldNumero.setEnabled(!true);
        jTextFieldCep.setEnabled(!true);
         jTextFieldBairro.setEnabled(!true);
         jTextFieldTel.setEnabled(!true);
      jButtonSalvar.setEnabled(!true);
       jLabelImagePaciente.setEnabled(!true);
        jButtonAddImagePaciente.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
      jTextFieldNomePaciente.setText("");
          jFormattedTextFieldNascimentoPaciente.setText("");
          jTextFieldSUS.setText("");
          jFormattedTextFieldRG.setText("");
          jTextFieldRua.setText("");
          jTextFieldBairro.setText("");
          jTextFieldCep.setText("");
          jTextFieldNumero.setText("");
          jTextFieldTel.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta =0;
        resposta =JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir o Paciente?");
        if(resposta==JOptionPane.YES_OPTION){
        mod.setRg(Integer.parseInt(jFormattedTextFieldRG.getText()));
        control.Excluir(mod);
           jTextFieldNomePaciente.setText("");
          jFormattedTextFieldNascimentoPaciente.setText("");
          jTextFieldSUS.setText("");
          jFormattedTextFieldRG.setText("");
          jTextFieldRua.setText("");
          jTextFieldBairro.setText("");
          jTextFieldCep.setText("");
          jTextFieldNumero.setText("");
          jTextFieldTel.setText("");
          jTextFieldNomePaciente.setEnabled(false);
          jFormattedTextFieldNascimentoPaciente.setEnabled(false);
          jFormattedTextFieldRG.setEnabled(false);
          jTextFieldSUS.setEnabled(false);
          jTextFieldRua.setEnabled(false);
           jTextFieldNumero.setEnabled(false);
           jTextFieldCep.setEnabled(false);
           jTextFieldBairro.setEnabled(false);
           jTextFieldTel.setEnabled(false);
          jButtonSalvar.setEnabled(false);  
          jButtonNovo.setEnabled(true);
          jButtonCancelar.setEnabled(false);
          jButtonEditar.setEnabled(false);
          jButtonExcluir.setEnabled(false);
           preencherTabela("select * from pacientes order by nome_paci");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
       mod.setPesquisa(jTextFieldPesquisa.getText());// Atributo pesquisa insere dentro do método de pesquisa o que o usuário digitou.
        BeansPaciente model = control.buscaPaciente(mod);// Chama o método buscaMedico.
        /*Função que envia o modelo (setPesquisa) e chamando o método (buscaMedico) enviando
        *por parâmetro (mod) o que o usuário digitou. 
        */
        jTextFieldNomePaciente.setText(model.getNome());
        jFormattedTextFieldNascimentoPaciente.setText(model.getNascimento());//Campo nome recebe o nome encontrado no banco.
        jFormattedTextFieldRG.setText(String.valueOf(model.getRg()));//Transforma o inteiro em String.
        jTextFieldSUS.setText(String.valueOf(model.getSus()));
        jTextFieldRua.setText(model.getRua());
        jTextFieldNumero.setText(String.valueOf(model.getNumero()));
        jTextFieldCep.setText(String.valueOf(model.getCep()));
        jTextFieldBairro.setText(model.getBairro());
        jTextFieldTel.setText(String.valueOf(model.getTelefone())); 
       preencherTabela("select *from pacientes where nome_paci like'%"+mod.getPesquisa()+"%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked
       String nome_paci=""+jTablePaciente.getValueAt(jTablePaciente.getSelectedRow(),0);
        conex.conexao();
        conex.executaSql("select *from pacientes where nome_paci='"+nome_paci+"'");
        try {
            conex.rs.first();
            jTextFieldNomePaciente.setText(conex.rs.getString("nome_paci"));
               jFormattedTextFieldRG.setText(conex.rs.getString("rg_paci"));
            jTextFieldSUS.setText(conex.rs.getString("sus_paci"));
            jTextFieldRua.setText(conex.rs.getString("rua_paci"));
            jTextFieldNumero.setText(conex.rs.getString("numero_paci"));
            jTextFieldCep.setText(conex.rs.getString("cep_paci"));
            jTextFieldBairro.setText(conex.rs.getString("bairro_paci"));
            jTextFieldTel.setText(conex.rs.getString("tel_paci"));
            jFormattedTextFieldNascimentoPaciente.setText(conex.rs.getString("nasci_paci"));
         
            
            
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar os Dados!\n"+ex.getMessage());
            
        }
        conex.desconecta();
    }//GEN-LAST:event_jTablePacienteMouseClicked

        public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Nome", "Nacimento", "RG", "Telefone"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
        
            do{
                dados.add(new Object[]{conex.rs.getString("nome_paci"), conex.rs.getString("nasci_paci"),conex.rs.getInt("rg_paci"), conex.rs.getString("tel_paci")});
            }while(conex.rs.next());//Enquanto houver dados ele vai percorrer o registro.
        }catch (SQLException ex){
            //JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList\n"+ex.getMessage());   
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {};
        
        jTablePaciente.setModel(modelo);
        jTablePaciente.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTablePaciente.getColumnModel().getColumn(0).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTablePaciente.getColumnModel().getColumn(1).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTablePaciente.getColumnModel().getColumn(2).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(3).setPreferredWidth(101);
        jTablePaciente.getColumnModel().getColumn(3).setResizable(false);
        jTablePaciente.getTableHeader().setReorderingAllowed(false);
        jTablePaciente.setAutoResizeMode(jTablePaciente.AUTO_RESIZE_OFF);// Bloqueia Tabela para redimensionamento.
        jTablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);// Usuário só pode selecionar um campo da tabela por vez.
        conex.desconecta();
    }
    

    /**
     * @param args the command line arguments
     */
   
           public static void main(String args[]) throws ClassNotFoundException {
       try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
           try {
               UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
           } catch (InstantiationException ex) {
               Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
           } catch (UnsupportedLookAndFeelException ex) {
               Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
           }
}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddImagePaciente;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimentoPaciente;
    private javax.swing.JTextField jFormattedTextFieldRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImagePaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldNomePaciente;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldSUS;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables
}
