/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConnection.conexaoBD;
import modeloDao.DaoEnfermeiros;
import modeloBeans.BeansEnfermeiro;
import modeloBeans.ModeloTabela;

public class FormEnfermeiro extends javax.swing.JFrame {
   
    BeansEnfermeiro mod = new BeansEnfermeiro();
    DaoEnfermeiros control = new DaoEnfermeiros();
    conexaoBD conex = new conexaoBD();
    int flag = 0;
        
    
    
    public FormEnfermeiro() {
        initComponents();
        preencherTabela("select *from enfermeiros order by nome_enfermeiro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAddImage = new javax.swing.JButton();
        jLabeImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnfermeiro = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldNomeEnfermeiro = new javax.swing.JTextField();
        jtCOD = new javax.swing.JTextField();
        jTextFieldCoren = new javax.swing.JTextField();
        jComboBoxEspecializacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Enfermeiros");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Sistema_Mais_Saude/icone3.png"));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Enfermeiros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 70, 60, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 70, 30, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("COREN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 122, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Especialidade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 120, 100, 30);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(30, 190, 90, 35);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(30, 230, 90, 35);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(30, 270, 90, 35);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(30, 310, 90, 35);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(30, 350, 90, 35);

        jButtonAddImage.setToolTipText("Click para adicionar Imagem");
        jButtonAddImage.setBorder(null);
        jButtonAddImage.setContentAreaFilled(false);
        jButtonAddImage.setEnabled(false);
        jButtonAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddImageActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddImage);
        jButtonAddImage.setBounds(20, 40, 120, 130);

        jLabeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile_icon.png"))); // NOI18N
        jLabeImage.setToolTipText("Click para Add Imagem");
        jLabeImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabeImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabeImage);
        jLabeImage.setBounds(20, 40, 120, 130);

        jTableEnfermeiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEnfermeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnfermeiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEnfermeiro);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 230, 454, 160);
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(140, 190, 240, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(390, 190, 100, 33);

        jTextFieldNomeEnfermeiro.setEnabled(false);
        jPanel1.add(jTextFieldNomeEnfermeiro);
        jTextFieldNomeEnfermeiro.setBounds(210, 70, 220, 30);

        jtCOD.setEnabled(false);
        jPanel1.add(jtCOD);
        jtCOD.setBounds(510, 70, 60, 30);

        jTextFieldCoren.setEnabled(false);
        jPanel1.add(jTextFieldCoren);
        jTextFieldCoren.setBounds(230, 120, 100, 30);

        jComboBoxEspecializacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditor", "Auxiliar", "Cardiologista", "Cirurgião ", "Cuidados Intensivos", "Dermatologista", "Instrumentista", "Estomaterapista", "Nefrologista", "Oncologista", "Técnico", "Urgência Emergencia" }));
        jComboBoxEspecializacao.setEnabled(false);
        jPanel1.add(jComboBoxEspecializacao);
        jComboBoxEspecializacao.setBounds(460, 120, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 640, 440);

        setSize(new java.awt.Dimension(668, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
      flag=1;  
      jTextFieldNomeEnfermeiro.setEnabled(true);
      jTextFieldCoren.setEnabled(true);
      jComboBoxEspecializacao.setEnabled(true);
      jButtonSalvar.setEnabled(true);
       jLabeImage.setEnabled(true);
        jButtonAddImage.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNomeEnfermeiro.setText("");
        jTextFieldCoren.setText("");
        jTextFieldPesquisa.setText("");
        jComboBoxEspecializacao.setSelectedItem(null);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
       jButtonPesquisar.setEnabled(false);
       jtCOD.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
      jTextFieldNomeEnfermeiro.setEnabled(!true);
      jTextFieldCoren.setEnabled(!true);
      jComboBoxEspecializacao.setEnabled(!true);
      jButtonSalvar.setEnabled(!true);
       jLabeImage.setEnabled(!true);
        jButtonAddImage.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jtCOD.setText("");
         jTextFieldNomeEnfermeiro.setText("");
         jTextFieldCoren.setText(""); 
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if (jTextFieldNomeEnfermeiro.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o Campo Nome para Continuar!");
          jTextFieldNomeEnfermeiro.requestFocus();
      }else if(jTextFieldCoren.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"Preencha o Campo COREN para Continuar!");
          jTextFieldCoren.requestFocus();
      }else
      if (flag==1){ 
      mod.setNome(jTextFieldNomeEnfermeiro.getText());
      mod.setEspecialidade((String) jComboBoxEspecializacao.getSelectedItem());
      mod.setCoren(Integer.parseInt(jTextFieldCoren.getText()));
      mod.setFotoPerfil((String) jLabeImage.getText());
      control.Salvar(mod);
      jTextFieldNomeEnfermeiro.setText("");
      jTextFieldCoren.setText("");
     // jComboBoxEspecializacao.setModel(new DefaultComboBoxModel());
      jTextFieldNomeEnfermeiro.setEnabled(false);
      jTextFieldCoren.setEnabled(false);
      jComboBoxEspecializacao.setEnabled(false);
      jButtonSalvar.setEnabled(false);
      jButtonCancelar.setEnabled(false);
       preencherTabela("select *from enfermeiros order by nome_enfermeiro");
       }else{
          mod.setCodigo(Integer.parseInt(jtCOD.getText()));
          mod.setNome(jTextFieldNomeEnfermeiro.getText());
          mod.setEspecialidade((String)jComboBoxEspecializacao.getSelectedItem());
          mod.setCoren(Integer.parseInt(jTextFieldCoren.getText()));
          control.Editar(mod);
          jtCOD.setText("");
          jTextFieldNomeEnfermeiro.setText("");
          jTextFieldCoren.setText(""); 
          jTextFieldNomeEnfermeiro.setEnabled(false);
          jTextFieldCoren.setEnabled(false);
          jComboBoxEspecializacao.setEnabled(false);
          jButtonSalvar.setEnabled(false);  
          jButtonNovo.setEnabled(true);
          jButtonCancelar.setEnabled(false);
           preencherTabela("select *from enfermeiros order by nome_enfermeiro");
          
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag=2;
      jTextFieldNomeEnfermeiro.setEnabled(true);
      jTextFieldCoren.setEnabled(true);
      jComboBoxEspecializacao.setEnabled(true);
      jButtonSalvar.setEnabled(true);
       jLabeImage.setEnabled(true);
        jButtonAddImage.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("select *from enfermeiros order by nome_enfermeiro");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta =0;
        resposta =JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir o Enfermeiro?");
        if(resposta==JOptionPane.YES_OPTION){
        mod.setCodigo(Integer.parseInt(jtCOD.getText()));
        control.Excluir(mod);
         jtCOD.setText("");
          jTextFieldNomeEnfermeiro.setText("");
          jTextFieldCoren.setText(""); 
          jtCOD.setText("");
          jComboBoxEspecializacao.setSelectedItem(null);
          jTextFieldNomeEnfermeiro.setEnabled(false);
          jTextFieldCoren.setEnabled(false);
          jComboBoxEspecializacao.setEnabled(false);
          jButtonSalvar.setEnabled(false);  
          jButtonNovo.setEnabled(true);
          jButtonCancelar.setEnabled(false);
          jButtonEditar.setEnabled(false);
          jButtonExcluir.setEnabled(false);
           preencherTabela("select *from enfermeiros order by nome_enfermeiro");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableEnfermeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnfermeiroMouseClicked
             String nome_enfermeiro=""+jTableEnfermeiro.getValueAt(jTableEnfermeiro.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select *from enfermeiros where nome_enfermeiro='"+nome_enfermeiro+"'");
        try {
            conex.rs.first();
            jtCOD.setText(String.valueOf(conex.rs.getInt("cod_enfermeiro")));
            jTextFieldNomeEnfermeiro.setText(conex.rs.getString("nome_enfermeiro"));
            jComboBoxEspecializacao.setSelectedItem(conex.rs.getString("especialidade_enfermeiro"));
            jTextFieldCoren.setText(conex.rs.getString("coren_enfermeiro"));
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar os Dados!\n"+ex.getMessage());
            
        }
        conex.desconecta();
    }//GEN-LAST:event_jTableEnfermeiroMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         mod.setPesquisa(jTextFieldPesquisa.getText());// Atributo pesquisa insere dentro do método de pesquisa o que o usuário digitou.
        BeansEnfermeiro model = control.buscaEnfermeiro(mod);// Chama o método buscaMedico.
        /*Função que envia o modelo (setPesquisa) e chamando o método (buscaMedico) enviando
        *por parâmetro (mod) o que o usuário digitou. 
        */
        jtCOD.setText(String.valueOf(model.getCodigo()));
        jTextFieldNomeEnfermeiro.setText(model.getNome());//Campo nome recebe o nome encontrado no banco.
        jTextFieldCoren.setText(String.valueOf(model.getCoren()));//Transforma o inteiro em String.
        jComboBoxEspecializacao.setSelectedItem(model.getEspecialidade());
        preencherTabela("select *from enfermeiros where nome_enfermeiro like'%"+mod.getPesquisa()+"%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddImageActionPerformed
                                               
       JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
            int opt = arquivo.showOpenDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION){
                File file = new File("Caminho");
                file = arquivo.getSelectedFile(); //Recebe O Caminho.
                
                ImageIcon imagem = new ImageIcon(arquivo.getSelectedFile().getPath());
                jLabeImage.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLabeImage.getWidth(),jLabeImage.getHeight(), Image.SCALE_DEFAULT)));
                
                
            }
    }//GEN-LAST:event_jButtonAddImageActionPerformed

     public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Especialidade", "COREN"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
        
            do{
                dados.add(new Object[]{conex.rs.getInt("cod_enfermeiro"), conex.rs.getString("nome_enfermeiro"),conex.rs.getString("especialidade_enfermeiro"), conex.rs.getInt("coren_enfermeiro")});
            }while(conex.rs.next());//Enquanto houver dados ele vai percorrer o registro.
        }catch (SQLException ex){
            //JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList\n"+ex.getMessage());   
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {};
        
        jTableEnfermeiro.setModel(modelo);
        jTableEnfermeiro.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTableEnfermeiro.getColumnModel().getColumn(0).setResizable(false);
        jTableEnfermeiro.getColumnModel().getColumn(1).setPreferredWidth(210);
        jTableEnfermeiro.getColumnModel().getColumn(1).setResizable(false);
        jTableEnfermeiro.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableEnfermeiro.getColumnModel().getColumn(2).setResizable(false);
        jTableEnfermeiro.getColumnModel().getColumn(3).setPreferredWidth(101);
        jTableEnfermeiro.getColumnModel().getColumn(3).setResizable(false);
        jTableEnfermeiro.getTableHeader().setReorderingAllowed(false);
        jTableEnfermeiro.setAutoResizeMode(jTableEnfermeiro.AUTO_RESIZE_OFF);// Bloqueia Tabela para redimensionamento.
        jTableEnfermeiro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);// Usuário só pode selecionar um campo da tabela por vez.
        conex.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEnfermeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddImage;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEspecializacao;
    private javax.swing.JLabel jLabeImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEnfermeiro;
    private javax.swing.JTextField jTextFieldCoren;
    private javax.swing.JTextField jTextFieldNomeEnfermeiro;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jtCOD;
    // End of variables declaration//GEN-END:variables
}
