/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import modeloBeans.BeansAgenda;
import modeloConnection.conexaoBD;
import modeloDao.DaoAgenda;
import modeloDao.DaoConsulta;
import modeloBeans.BeansConsulta;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


public class FormConsulta extends javax.swing.JFrame {
   conexaoBD conex = new conexaoBD();
    String cod_agenda;
    BeansAgenda agen = new BeansAgenda();
    DaoAgenda daoAgenda= new DaoAgenda();
    BeansConsulta consulta = new BeansConsulta();
    DaoConsulta daoConsulta = new DaoConsulta();
    
    /**
     * Creates new form FormConsulta
     */
    public FormConsulta(String codigo) {
        initComponents();
        cod_agenda = codigo;
        int cod = Integer.parseInt(cod_agenda);
        agen = daoAgenda.BuscaAgendamentoPorCodigo(cod);
        jTextFieldNome.setText(agen.getNomePac());
        jFormattedTextFieldNascimento.setText(agen.getPacienteNasci());
        jTextAreaMotivo.setText(agen.getMotivo());
        jLabelMédico.setText(agen.getNomeMed());
        jLabelCRM.setText(agen.getCRM());
        jTextFieldSus.setText(agen.getSus());
       
      
        
    
     //A Linha Abaixo Exibe a Data Atual do Sistema
    
    Date  data = new Date();
    DateFormat formatar = DateFormat.getDateInstance(DateFormat.LONG);
    jTextFieldData.setText(formatar.format(data));
    
    //A Linha Abaixo exibe a Hora Atual do Sistema
     Timer timer = new Timer(1000, new hora());
        timer.start();
    
    }
     
   

    private FormConsulta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldNascimento = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMotivo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldHorario = new javax.swing.JTextField();
        jLabelCodAgenda = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaReceita = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDiagnóstico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelMédico = new javax.swing.JLabel();
        jLabelCRM = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha de Atendimento");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Sistema_Mais_Saude/icone3.png"));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 50, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Motivo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 57, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nascimento");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 20, 100, 30);

        jTextFieldNome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(70, 20, 330, 30);

        jFormattedTextFieldNascimento.setEnabled(false);
        jFormattedTextFieldNascimento.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jFormattedTextFieldNascimento);
        jFormattedTextFieldNascimento.setBounds(560, 20, 170, 30);

        jTextAreaMotivo.setColumns(20);
        jTextAreaMotivo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextAreaMotivo.setRows(5);
        jTextAreaMotivo.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaMotivo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 710, 130);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Data");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 70, 50, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Horário");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(240, 70, 70, 30);

        jTextFieldData.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextFieldData.setEnabled(false);
        jPanel1.add(jTextFieldData);
        jTextFieldData.setBounds(70, 70, 140, 30);

        jTextFieldHorario.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextFieldHorario.setEnabled(false);
        jPanel1.add(jTextFieldHorario);
        jTextFieldHorario.setBounds(310, 70, 50, 30);
        jPanel1.add(jLabelCodAgenda);
        jLabelCodAgenda.setBounds(320, 74, 80, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("SUS");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(430, 70, 33, 30);

        jTextFieldSus.setEnabled(false);
        jPanel1.add(jTextFieldSus);
        jTextFieldSus.setBounds(470, 70, 260, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 760, 280);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 80, 20);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setText("Finalizar Atendimento");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(310, 670, 170, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jTextAreaReceita.setColumns(20);
        jTextAreaReceita.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextAreaReceita.setRows(5);
        jScrollPane2.setViewportView(jTextAreaReceita);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 150, 700, 140);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Receita");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 130, 60, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Diagnóstico ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 80, 100, 30);

        jTextFieldDiagnóstico.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel2.add(jTextFieldDiagnóstico);
        jTextFieldDiagnóstico.setBounds(120, 80, 590, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Médico:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 10, 70, 50);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("CRM");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(470, 20, 50, 30);

        jLabelMédico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jLabelMédico);
        jLabelMédico.setBounds(90, 20, 320, 30);

        jLabelCRM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jLabelCRM);
        jLabelCRM.setBounds(520, 20, 190, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 350, 760, 310);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Formulário de Atendimento Médico");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 10, 320, 20);

        setSize(new java.awt.Dimension(804, 760));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    conex.conexao();
     Connection con = conexaoBD.conexao();
        if(jTextFieldDiagnóstico.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Preencha o Campo Diagnóstico para Continuar!");
            jTextFieldDiagnóstico.requestFocus();
    }else{
       consulta.setNomePaci(jTextFieldNome.getText());
       consulta.setNasciPaci(jFormattedTextFieldNascimento.getText());
       consulta.setMotivoAtendimento(jTextAreaMotivo.getText());
       consulta.setNomeMedico(jLabelMédico.getText());
       consulta.setCrm(Integer.parseInt(jLabelCRM.getText()));
       consulta.setDiagnostico(jTextFieldDiagnóstico.getText());
       consulta.setReceita(jTextAreaReceita.getText());
       consulta.setStatusAtendimento("Paciente Atendido");
       consulta.setDataAtendimento(jTextFieldData.getText());
       consulta.setHorarioAtendimento(jTextFieldHorario.getText());
       consulta.setSus(jTextFieldSus.getText());
        daoConsulta.SalvarConsulta(consulta);
       conex.desconecta();
  
       conex.conexao();
        
       agen.setStatus("Paciente Atendido!");
       daoAgenda.FinalizarConsulta(agen);
       
       
      int confirm = JOptionPane.showConfirmDialog(null, "Deseja Imprmir a Ficha de Atendimento?", "Atenção",JOptionPane.YES_NO_OPTION );
      if (confirm== JOptionPane.YES_OPTION){
          InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("relatorios/Ficha de Atendimento3.jasper");
           JasperPrint jasperPrint= null;
          
          try {
              jasperPrint = JasperFillManager.fillReport(caminhoRelatorio, null, con);
              
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao Imprimir Ficha de Atendimeno!\n"+ex);
          }
          JasperViewer view = new JasperViewer (jasperPrint, false);
          view.setVisible(true);
          
      }
    }
   
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelCodAgenda;
    private javax.swing.JLabel jLabelMédico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaMotivo;
    private javax.swing.JTextArea jTextAreaReceita;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldDiagnóstico;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSus;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener {
    @Override   
    public void actionPerformed (ActionEvent e){
    Calendar now = Calendar.getInstance();    
    jTextFieldHorario.setText(String.format("%1$tH:%1$tM", now));
}
}
}
