/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import static java.util.Arrays.stream;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.plaf.basic.BasicMenuItemUI;
import modeloConnection.conexaoBD;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author rafa
 */
public class telaPrincipal extends javax.swing.JFrame {
    conexaoBD conecta = new conexaoBD();
    FormMedico tela = new FormMedico();
    FormUsuario telaUsu = new FormUsuario();
    FormPaciente telaPaci = new FormPaciente();
    FormEnfermeiro telaEnf = new FormEnfermeiro();
    FormAgenda telaAgenda = new FormAgenda();
    FormAgendamento telaAgendamento = new FormAgendamento();
    FormAgendaMédico telaAgendaMédico = new FormAgendaMédico();
   
    Color Indigo = new Color(8,59,102);
     Color Navy = new Color(86,104,140); 
     
   
   
    
   
    public telaPrincipal(String usuario) {
       
        this.setUndecorated(true);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        
        double width = toolkit.getScreenSize().getWidth();
        double height = toolkit.getScreenSize().getHeight();
        
       this.setSize((int)width, (int)height);
        
        initComponents();
        jLabel2.setText(usuario);
        conecta.conexao();
        //Altera a Cor do JMenu
        jMenuBar1.setOpaque(true);
        jMenuBar1.setUI(new BasicMenuBarUI() {
        public void paint(Graphics g, JComponent c) {
            g.setColor(Indigo);
            g.fillRect(0, 0, c.getWidth(), c.getHeight());
        }
    });

    jMenuItemAgendaPacientes.setOpaque(true);
    
        //Data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLabelData.setText(formato.format(dataSistema));
        
        
        //Hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
       
        
        
    }

    private telaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBorda = new javax.swing.JLabel();
        jLabelLupa1 = new javax.swing.JLabel();
        jLabelLupa3 = new javax.swing.JLabel();
        jLabelPlus2 = new javax.swing.JLabel();
        jLabelPlus3 = new javax.swing.JLabel();
        jLabelPlus4 = new javax.swing.JLabel();
        jLabelPlus5 = new javax.swing.JLabel();
        jLabelPlus6 = new javax.swing.JLabel();
        jLabelPlus8 = new javax.swing.JLabel();
        jLabelPlus9 = new javax.swing.JLabel();
        jLabelPlus = new javax.swing.JLabel();
        jLabelAgendamentoConsulta = new javax.swing.JLabel();
        jLabelCadastroPacientes = new javax.swing.JLabel();
        jLabelResultadoExames = new javax.swing.JLabel();
        jLabelProcedimentos = new javax.swing.JLabel();
        jLabelBuscaExames = new javax.swing.JLabel();
        CadastroRN = new javax.swing.JLabel();
        jLabelRX = new javax.swing.JLabel();
        jLabelCadastroMedicos = new javax.swing.JLabel();
        jLabelCadastroEnfermeiros = new javax.swing.JLabel();
        jLabelCadastroUsuarios = new javax.swing.JLabel();
        jLabelRadiotivo = new javax.swing.JLabel();
        jLabelMedicacao = new javax.swing.JLabel();
        jLabelPlus10 = new javax.swing.JLabel();
        jButtonMedicamento = new javax.swing.JButton();
        jButtonCadMed = new javax.swing.JButton();
        jButtonCadUsuario = new javax.swing.JButton();
        jButtonCadEnfermeiro = new javax.swing.JButton();
        jButtonCadPaciente = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jButtonAgendamento = new javax.swing.JButton();
        jButtonExames = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonAgendaPacientes = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBordaDataHora = new javax.swing.JLabel();
        jLabelPlanodeFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuCadMédicos = new javax.swing.JMenuItem();
        jMenuItemCadEnfermeiros = new javax.swing.JMenuItem();
        jMenuItemCadPacientes = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemRelPacientes = new javax.swing.JMenuItem();
        jMenuItemRelMédicos = new javax.swing.JMenuItem();
        jMenuItemRelEnfermeiros = new javax.swing.JMenuItem();
        jMenuItemRelUsuarios = new javax.swing.JMenuItem();
        jMenuItemRelConsultas = new javax.swing.JMenuItem();
        jMenuAgendaPacientes = new javax.swing.JMenu();
        jMenuItemAgendarConsulta = new javax.swing.JMenuItem();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenuItemAgendaPacientes = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabelBorda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo-preto-transparente-png-1.png"))); // NOI18N
        jLabelBorda.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mais Saúde Sistema de Gerenciamento Hospitalar");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Sistema_Mais_Saude/icone3.png")
        );
        getContentPane().setLayout(null);

        jLabelLupa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        getContentPane().add(jLabelLupa1);
        jLabelLupa1.setBounds(370, 540, 40, 32);

        jLabelLupa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        getContentPane().add(jLabelLupa3);
        jLabelLupa3.setBounds(540, 540, 40, 32);

        jLabelPlus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_40632.png"))); // NOI18N
        getContentPane().add(jLabelPlus2);
        jLabelPlus2.setBounds(540, 210, 22, 30);

        jLabelPlus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_40632.png"))); // NOI18N
        getContentPane().add(jLabelPlus3);
        jLabelPlus3.setBounds(860, 210, 30, 30);

        jLabelPlus4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_40632.png"))); // NOI18N
        getContentPane().add(jLabelPlus4);
        jLabelPlus4.setBounds(370, 210, 22, 30);

        jLabelPlus5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        getContentPane().add(jLabelPlus5);
        jLabelPlus5.setBounds(700, 210, 30, 30);
        getContentPane().add(jLabelPlus6);
        jLabelPlus6.setBounds(410, 20, 0, 0);

        jLabelPlus8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_40632.png"))); // NOI18N
        getContentPane().add(jLabelPlus8);
        jLabelPlus8.setBounds(540, 370, 22, 30);

        jLabelPlus9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_40632.png"))); // NOI18N
        getContentPane().add(jLabelPlus9);
        jLabelPlus9.setBounds(370, 370, 22, 30);

        jLabelPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        getContentPane().add(jLabelPlus);
        jLabelPlus.setBounds(860, 370, 32, 30);

        jLabelAgendamentoConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAgendamentoConsulta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentoConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgendamentoConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAgendamentoConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAgendamentoConsultaMouseExited(evt);
            }
        });
        getContentPane().add(jLabelAgendamentoConsulta);
        jLabelAgendamentoConsulta.setBounds(330, 340, 210, 20);

        jLabelCadastroPacientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroPacientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelCadastroPacientes);
        jLabelCadastroPacientes.setBounds(530, 340, 150, 20);

        jLabelResultadoExames.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResultadoExames.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResultadoExames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelResultadoExames);
        jLabelResultadoExames.setBounds(850, 340, 160, 20);

        jLabelProcedimentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelProcedimentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProcedimentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelProcedimentos);
        jLabelProcedimentos.setBounds(840, 500, 180, 20);

        jLabelBuscaExames.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBuscaExames.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscaExames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelBuscaExames);
        jLabelBuscaExames.setBounds(400, 670, 80, 20);

        CadastroRN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CadastroRN.setForeground(new java.awt.Color(255, 255, 255));
        CadastroRN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(CadastroRN);
        CadastroRN.setBounds(700, 340, 140, 20);

        jLabelRX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelRX);
        jLabelRX.setBounds(720, 670, 100, 20);

        jLabelCadastroMedicos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroMedicos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelCadastroMedicos);
        jLabelCadastroMedicos.setBounds(340, 500, 190, 20);

        jLabelCadastroEnfermeiros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroEnfermeiros.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroEnfermeiros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelCadastroEnfermeiros);
        jLabelCadastroEnfermeiros.setBounds(520, 500, 170, 20);

        jLabelCadastroUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelCadastroUsuarios);
        jLabelCadastroUsuarios.setBounds(690, 500, 150, 20);

        jLabelRadiotivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRadiotivo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRadiotivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelRadiotivo);
        jLabelRadiotivo.setBounds(850, 670, 160, 20);

        jLabelMedicacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMedicacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMedicacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelMedicacao);
        jLabelMedicacao.setBounds(560, 670, 100, 20);

        jLabelPlus10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_40632.png"))); // NOI18N
        getContentPane().add(jLabelPlus10);
        jLabelPlus10.setBounds(700, 370, 30, 30);

        jButtonMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicacao_icon.png"))); // NOI18N
        jButtonMedicamento.setToolTipText("Consultar Medicações");
        jButtonMedicamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonMedicamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMedicamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMedicamentoMouseExited(evt);
            }
        });
        getContentPane().add(jButtonMedicamento);
        jButtonMedicamento.setBounds(550, 550, 120, 120);
        jButtonMedicamento.getAccessibleContext().setAccessibleDescription("");

        jButtonCadMed.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medico_icon.png"))); // NOI18N
        jButtonCadMed.setToolTipText("Adicionar e Consultar Cadastro de Médicos");
        jButtonCadMed.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCadMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadMedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadMedMouseExited(evt);
            }
        });
        jButtonCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadMed);
        jButtonCadMed.setBounds(380, 380, 120, 120);

        jButtonCadUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exames_icon.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("Adicionar e Consultar Cadastro de Usuários");
        jButtonCadUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCadUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadUsuarioMouseExited(evt);
            }
        });
        jButtonCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadUsuario);
        jButtonCadUsuario.setBounds(710, 380, 120, 120);

        jButtonCadEnfermeiro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadEnfermeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enfermeira_icon.png"))); // NOI18N
        jButtonCadEnfermeiro.setToolTipText("Adicionar e Consultar Cadastro de Enfermeiros");
        jButtonCadEnfermeiro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCadEnfermeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadEnfermeiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadEnfermeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadEnfermeiroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadEnfermeiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadEnfermeiroMouseExited(evt);
            }
        });
        jButtonCadEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEnfermeiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadEnfermeiro);
        jButtonCadEnfermeiro.setBounds(550, 380, 120, 120);

        jButtonCadPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paciente_icon.png"))); // NOI18N
        jButtonCadPaciente.setToolTipText("Adicionar e Consultar Cadastro de Pacientes");
        jButtonCadPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCadPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadPacienteMouseExited(evt);
            }
        });
        jButtonCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadPaciente);
        jButtonCadPaciente.setBounds(550, 220, 120, 120);

        jButtonRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatório_icon.png"))); // NOI18N
        jButtonRelatorio.setToolTipText("Gerar Relatório de Atendimento");
        jButtonRelatorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRelatorioMouseExited(evt);
            }
        });
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorio);
        jButtonRelatorio.setBounds(870, 220, 120, 120);

        jButtonAgendamento.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agendamento_icon.png"))); // NOI18N
        jButtonAgendamento.setToolTipText("Adicionar e Pesquisar Consultas");
        jButtonAgendamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgendamento.setRolloverEnabled(true);
        jButtonAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAgendamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgendamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAgendamentoMousePressed(evt);
            }
        });
        jButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendamento);
        jButtonAgendamento.setBounds(380, 220, 120, 120);
        jButtonAgendamento.getAccessibleContext().setAccessibleDescription("");

        jButtonExames.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exames2_icon.png"))); // NOI18N
        jButtonExames.setToolTipText("Adicionar e Pesquisar Exames");
        jButtonExames.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonExames.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonExamesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonExamesMouseExited(evt);
            }
        });
        jButtonExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExamesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExames);
        jButtonExames.setBounds(380, 550, 120, 120);
        jButtonExames.getAccessibleContext().setAccessibleDescription("");

        jButtonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agenda_icon.png"))); // NOI18N
        jButtonAgenda.setToolTipText("Pesquisar Consultas Agendadas");
        jButtonAgenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgendaMouseExited(evt);
            }
        });
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(710, 220, 120, 120);
        jButtonAgenda.getAccessibleContext().setAccessibleDescription("");

        jButtonAgendaPacientes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgendaPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medical_report.png"))); // NOI18N
        jButtonAgendaPacientes.setToolTipText("Agenda de Pacientes");
        jButtonAgendaPacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAgendaPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgendaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAgendaPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgendaPacientesMouseExited(evt);
            }
        });
        jButtonAgendaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendaPacientes);
        jButtonAgendaPacientes.setBounds(870, 380, 120, 120);
        jButtonAgendaPacientes.getAccessibleContext().setAccessibleDescription("");

        jButtonLogout.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_icone.png"))); // NOI18N
        jButtonLogout.setToolTipText("Trocar de Usuário");
        jButtonLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout);
        jButtonLogout.setBounds(710, 550, 120, 120);

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit2.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair do Sistema");
        jButtonSair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMouseExited(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(870, 550, 120, 120);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mais_Saude_BackGround.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(490, 10, 400, 190);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 360, 34, 14);

        jPanel1.setBackground(new java.awt.Color(8, 59, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabelData);
        jLabelData.setBounds(1230, 10, 130, 30);

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabelHora);
        jLabelHora.setBounds(1240, 0, 110, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 10, 180, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 20);

        jLabelBordaDataHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelBordaDataHora);
        jLabelBordaDataHora.setBounds(1230, 0, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 710, 1370, 40);

        jLabelPlanodeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background2.jpg"))); // NOI18N
        jLabelPlanodeFundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabelPlanodeFundo);
        jLabelPlanodeFundo.setBounds(-10, -10, 1400, 910);

        jMenuBar1.setBackground(new java.awt.Color(8, 59, 102));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setAutoscrolls(true);

        jMenuCadastros.setForeground(new java.awt.Color(255, 255, 255));
        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuCadMédicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadMédicos.setText("Médicos");
        jMenuCadMédicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadMédicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadMédicos);

        jMenuItemCadEnfermeiros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadEnfermeiros.setText("Enfermeiros");
        jMenuItemCadEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEnfermeirosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadEnfermeiros);

        jMenuItemCadPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadPacientes.setText("Pacientes");
        jMenuItemCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadPacientes);

        jMenuItemCadUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Relatórios");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemRelPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelPacientes.setText("Pacientes");
        jMenuItemRelPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRelPacientes);

        jMenuItemRelMédicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelMédicos.setText("Médicos");
        jMenuItemRelMédicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelMédicosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRelMédicos);

        jMenuItemRelEnfermeiros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelEnfermeiros.setText("Enfermeiros");
        jMenuItemRelEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelEnfermeirosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRelEnfermeiros);

        jMenuItemRelUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelUsuarios.setText("Usuários");
        jMenuItemRelUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRelUsuarios);

        jMenuItemRelConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelConsultas.setText("Consultas");
        jMenuItemRelConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRelConsultas);

        jMenuBar1.add(jMenu1);

        jMenuAgendaPacientes.setForeground(new java.awt.Color(255, 255, 255));
        jMenuAgendaPacientes.setText("Agenda");
        jMenuAgendaPacientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItemAgendarConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemAgendarConsulta.setText("Agendar Consulta");
        jMenuItemAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendarConsultaActionPerformed(evt);
            }
        });
        jMenuAgendaPacientes.add(jMenuItemAgendarConsulta);

        jMenuItemAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemAgenda.setText("Consultas Agendadas");
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        jMenuAgendaPacientes.add(jMenuItemAgenda);

        jMenuItemAgendaPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAgendaPacientes.setText("Agenda de Pacientes");
        jMenuItemAgendaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaPacientesActionPerformed(evt);
            }
        });
        jMenuAgendaPacientes.add(jMenuItemAgendaPacientes);

        jMenuBar1.add(jMenuAgendaPacientes);

        jMenuSair.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuLogout);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1374, 794));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEnfermeiroActionPerformed
             try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                /*FormMedico tela = new FormMedico();
                tela.setVisible(true);*/
             if(tela==null){
                 telaEnf = new FormEnfermeiro();
                 telaEnf.setVisible(true);
             }else{
                 telaEnf.setVisible(true);
             }   
                
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
        
                
        }
             
             
             
    }//GEN-LAST:event_jButtonCadEnfermeiroActionPerformed

    private void jButtonCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedActionPerformed
       //Controle de Acesso de Usuários
        try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                
             if(tela==null){
                 tela = new FormMedico();
                 tela.setVisible(true);
             }else{
                 tela.setVisible(true);
             }   
                
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
        
                
        }
    }//GEN-LAST:event_jButtonCadMedActionPerformed

    private void jMenuCadMédicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadMédicosActionPerformed
          try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                /*FormMedico tela = new FormMedico();
                tela.setVisible(true);*/
             if(tela==null){
                 tela = new FormMedico();
                 tela.setVisible(true);
             }else{
                 tela.setVisible(true);
             }   
                
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
        
                
        }
      
    }//GEN-LAST:event_jMenuCadMédicosActionPerformed

    private void jButtonCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacienteActionPerformed
        if (telaPaci==null){
            telaPaci = new FormPaciente();
            telaPaci.setVisible(true);
        
        }else{
        telaPaci.setVisible(true);
    }
    }//GEN-LAST:event_jButtonCadPacienteActionPerformed

    private void jMenuItemCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacientesActionPerformed
               if (telaPaci==null){
            telaPaci = new FormPaciente();
            telaPaci.setVisible(true);
        
        }else{
        telaPaci.setVisible(true);
    }
    }//GEN-LAST:event_jMenuItemCadPacientesActionPerformed

    private void jButtonCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioActionPerformed
           try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
               if (telaUsu==null){
                   telaUsu = new FormUsuario();
                   telaUsu.setVisible(true);
               
               }else{
                   telaUsu.setVisible(true);
               }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Controle de Cadastro de Usuários");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Controle de Cadstro de Usuários");
             
        }
      
     
    }//GEN-LAST:event_jButtonCadUsuarioActionPerformed

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
            try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
               if(telaUsu==null){
                   telaUsu = new FormUsuario();
                   telaUsu.setVisible(true);
               
               }else{
                   telaUsu.setVisible(true);
               }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Controle de Cadastro de Usuários");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Controle de Cadastro de Usuários");
             
        }
      
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
      int resposta = 0;
       resposta = JOptionPane.showConfirmDialog(null,"Deseja Sair do Sistema Mais Saúde?","Atenção", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION){
         System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(null,"Deseja Trocar de Usuário?","Atenção", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION){
        dispose(); 
        telaLogin tela = new telaLogin();
        tela.setVisible(true);
        }
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuItemCadEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEnfermeirosActionPerformed
               try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                /*FormMedico tela = new FormMedico();
                tela.setVisible(true);*/
             if(tela==null){
                 telaEnf = new FormEnfermeiro();
                 telaEnf.setVisible(true);
             }else{
                 telaEnf.setVisible(true);
             }   
                
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Administrador para Acessar o Formulário de Médicos");
        
                
        }
    }//GEN-LAST:event_jMenuItemCadEnfermeirosActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
     
        if(telaAgenda==null){
                 telaAgenda = new FormAgenda();
                 telaAgenda.setVisible(true);
                
     }else{
         telaAgenda.setVisible(true);
     }
     
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonAgendamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendamentoMousePressed
      
    }//GEN-LAST:event_jButtonAgendamentoMousePressed

    private void jButtonAgendamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendamentoMouseEntered
         jButtonAgendamento.setBackground(Indigo);
         jLabelAgendamentoConsulta.setForeground(Indigo);
    }//GEN-LAST:event_jButtonAgendamentoMouseEntered

    private void jLabelAgendamentoConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgendamentoConsultaMouseEntered
        
    }//GEN-LAST:event_jLabelAgendamentoConsultaMouseEntered

    private void jButtonAgendamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendamentoMouseExited
        jButtonAgendamento.setBackground(Color.WHITE);
          jLabelAgendamentoConsulta.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonAgendamentoMouseExited

    private void jLabelAgendamentoConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgendamentoConsultaMouseExited
      
    }//GEN-LAST:event_jLabelAgendamentoConsultaMouseExited

    private void jButtonCadPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadPacienteMouseEntered
        jButtonCadPaciente.setBackground(Indigo);
         jLabelCadastroPacientes.setForeground(Indigo);
    }//GEN-LAST:event_jButtonCadPacienteMouseEntered

    private void jButtonCadPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadPacienteMouseExited
        jButtonCadPaciente.setBackground(Color.WHITE);
         jLabelCadastroPacientes.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonCadPacienteMouseExited

    private void jButtonAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendaMouseEntered
         jButtonAgenda.setBackground(Indigo);
         CadastroRN.setForeground(Indigo);
    }//GEN-LAST:event_jButtonAgendaMouseEntered

    private void jButtonAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendaMouseExited
      jButtonAgenda.setBackground(Color.WHITE);
         CadastroRN.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonAgendaMouseExited

    private void jButtonRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelatorioMouseEntered
        jButtonRelatorio.setBackground(Indigo);
         jLabelResultadoExames.setForeground(Indigo);
    }//GEN-LAST:event_jButtonRelatorioMouseEntered

    private void jButtonRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelatorioMouseExited
        jButtonRelatorio.setBackground(Color.WHITE);
         jLabelResultadoExames.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonRelatorioMouseExited

    private void jButtonAgendaPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendaPacientesMouseEntered
       jButtonAgendaPacientes.setBackground(Indigo);
         jLabelProcedimentos.setForeground(Indigo);
    }//GEN-LAST:event_jButtonAgendaPacientesMouseEntered

    private void jButtonAgendaPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendaPacientesMouseExited
       jButtonAgendaPacientes.setBackground(Color.WHITE);
         jLabelProcedimentos.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonAgendaPacientesMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
      jButtonLogout.setBackground(Indigo);
         jLabelRX.setForeground(Indigo);
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
      jButtonLogout.setBackground(Color.WHITE);
         jLabelRX.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonCadMedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadMedMouseEntered
        jButtonCadMed.setBackground(Indigo);
         jLabelCadastroMedicos.setForeground(Indigo);
    }//GEN-LAST:event_jButtonCadMedMouseEntered

    private void jButtonCadMedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadMedMouseExited
         jButtonCadMed.setBackground(Color.WHITE);
         jLabelCadastroMedicos.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonCadMedMouseExited

    private void jButtonCadEnfermeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadEnfermeiroMouseClicked
      
    }//GEN-LAST:event_jButtonCadEnfermeiroMouseClicked

    private void jButtonCadEnfermeiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadEnfermeiroMouseExited
       jButtonCadEnfermeiro.setBackground(Color.WHITE);
         jLabelCadastroEnfermeiros.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonCadEnfermeiroMouseExited

    private void jButtonCadUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioMouseEntered
        jButtonCadUsuario.setBackground(Indigo);
         jLabelCadastroUsuarios.setForeground(Indigo);
    }//GEN-LAST:event_jButtonCadUsuarioMouseEntered

    private void jButtonCadUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioMouseExited
            jButtonCadUsuario.setBackground(Color.WHITE);
         jLabelCadastroUsuarios.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonCadUsuarioMouseExited

    private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseEntered
           jButtonSair.setBackground(Indigo);
         jLabelRadiotivo.setForeground(Indigo);
    }//GEN-LAST:event_jButtonSairMouseEntered

    private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseExited
          jButtonSair.setBackground(Color.WHITE);
         jLabelRadiotivo.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonSairMouseExited

    private void jButtonCadEnfermeiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadEnfermeiroMouseEntered
         jButtonCadEnfermeiro.setBackground(Indigo);
         jLabelCadastroEnfermeiros.setForeground(Indigo);
    }//GEN-LAST:event_jButtonCadEnfermeiroMouseEntered

    private void jButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentoActionPerformed
      if (telaAgendamento==null){
          telaAgendamento = new FormAgendamento();
          telaAgendamento.setVisible(true);
      }else{
          telaAgendamento.setVisible(true);
      }
        
    }//GEN-LAST:event_jButtonAgendamentoActionPerformed

    private void jMenuItemAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendarConsultaActionPerformed
      
           if (telaAgendamento==null){
          telaAgendamento = new FormAgendamento();
          telaAgendamento.setVisible(true);
      }else{
          telaAgendamento.setVisible(true);
      }
        
    }//GEN-LAST:event_jMenuItemAgendarConsultaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
       int resposta = 0;
       resposta = JOptionPane.showConfirmDialog(null,"Deseja Sair do Sistema Mais Saúde?","Atenção", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION){
         System.exit(0);
        }
       
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(null,"Deseja Trocar de Usuário?","Atenção", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION){
        dispose(); 
        telaLogin tela = new telaLogin();
        tela.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed

        if(telaAgenda==null){
                 telaAgenda = new FormAgenda();
                 telaAgenda.setVisible(true);
     }else{
         telaAgenda.setVisible(true);
     }
     
    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    private void jButtonAgendaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaPacientesActionPerformed
      
           try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Médico")||conecta.rs.getString("usu_tipo").equals("Administrador")){
             if(telaAgendaMédico==null){
                telaAgendaMédico = new FormAgendaMédico();
                telaAgendaMédico.setVisible(true);
             }else{
                 telaAgendaMédico.setVisible(true);
             }   
                
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Médico para Acessar a Agenda de Pacientes");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Médico para Acessar a Agenda de Pacientes");
        }
        
    }//GEN-LAST:event_jButtonAgendaPacientesActionPerformed

    private void jMenuItemAgendaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaPacientesActionPerformed
              try { 
            conecta.executaSql("select *from usuarios where usu_nome='"+jLabel2.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("usu_tipo").equals("Médico")||conecta.rs.getString("usu_tipo").equals("Administrador")){
             if(telaAgendaMédico==null){
                telaAgendaMédico = new FormAgendaMédico();
                telaAgendaMédico.setVisible(true);
             }else{
                 telaAgendaMédico.setVisible(true);
             }   
                
            }else{
                JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Médico para Acessar a Agenda de Pacientes");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Necessária a Permissão de Médico para Acessar a Agenda de Pacientes");
        }
    }//GEN-LAST:event_jMenuItemAgendaPacientesActionPerformed

    private void jButtonMedicamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMedicamentoMouseExited
        jButtonMedicamento.setBackground(Color.WHITE);
        jLabelMedicacao.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonMedicamentoMouseExited

    private void jButtonMedicamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMedicamentoMouseEntered
       jButtonMedicamento.setBackground(Indigo);
        jLabelMedicacao.setForeground(Indigo);
    }//GEN-LAST:event_jButtonMedicamentoMouseEntered

    private void jButtonExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExamesActionPerformed

    private void jButtonExamesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExamesMouseExited
        jButtonExames.setBackground(Color.WHITE);
        jLabelBuscaExames.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonExamesMouseExited

    private void jButtonExamesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExamesMouseEntered
      jButtonExames.setBackground(Indigo);
        jLabelBuscaExames.setForeground(Indigo);
    }//GEN-LAST:event_jButtonExamesMouseEntered

    private void jMenuItemRelPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelPacientesActionPerformed
      
     Connection con = conexaoBD.conexao();
      
      
      int confirm = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatório?", "Atenção",JOptionPane.YES_NO_OPTION );
      if (confirm== JOptionPane.YES_OPTION){
          InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("relatorios/relatoriodePacientes.jasper");
           JasperPrint jasperPrint= null;
          
          try {
              jasperPrint = JasperFillManager.fillReport(caminhoRelatorio, null, con);
              
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao Gerar Relatório!\n"+ex);
          }
          JasperViewer view = new JasperViewer (jasperPrint, false);
          view.setVisible(true);
          
      }
      
    }//GEN-LAST:event_jMenuItemRelPacientesActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
  
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemRelEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelEnfermeirosActionPerformed
          
     Connection con = conexaoBD.conexao();
      
      
      int confirm = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatório?", "Atenção",JOptionPane.YES_NO_OPTION );
      if (confirm== JOptionPane.YES_OPTION){
          InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("relatorios/Relatório de Enfermeiros.jasper");
           JasperPrint jasperPrint= null;
          
          try {
              jasperPrint = JasperFillManager.fillReport(caminhoRelatorio, null, con);
              
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao Gerar Relatório!\n"+ex);
          }
          JasperViewer view = new JasperViewer (jasperPrint, false);
          view.setVisible(true);
          
      }
      
    }//GEN-LAST:event_jMenuItemRelEnfermeirosActionPerformed

    private void jMenuItemRelMédicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelMédicosActionPerformed
             
     Connection con = conexaoBD.conexao();
      
      
      int confirm = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatório?", "Atenção",JOptionPane.YES_NO_OPTION );
      if (confirm== JOptionPane.YES_OPTION){
          InputStream caminhoRelatorio =this.getClass().getClassLoader().getResourceAsStream("relatorios/Relatório de Médicos.jasper");
           JasperPrint jasperPrint= null;
          
          try {
              jasperPrint = JasperFillManager.fillReport(caminhoRelatorio, null, con);
              
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao Gerar Relatório!\n"+ex);
          }
          JasperViewer view = new JasperViewer (jasperPrint, false);
          view.setVisible(true);
          
      }
      
    }//GEN-LAST:event_jMenuItemRelMédicosActionPerformed

    private void jMenuItemRelUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelUsuariosActionPerformed
      
     Connection con = conexaoBD.conexao();
      
      
      int confirm = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatório?", "Atenção",JOptionPane.YES_NO_OPTION );
      if (confirm== JOptionPane.YES_OPTION){
          InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("relatorios/Relatório de Usuários.jasper");
           JasperPrint jasperPrint= null;
          
          try {
              jasperPrint = JasperFillManager.fillReport(caminhoRelatorio, null, con);
              
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao Gerar Relatório!\n"+ex);
          }
          JasperViewer view = new JasperViewer (jasperPrint, false);
          view.setVisible(true);
          
      }
      
    }//GEN-LAST:event_jMenuItemRelUsuariosActionPerformed

    private void jMenuItemRelConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelConsultasActionPerformed
     Connection con = conexaoBD.conexao();
      
      
      int confirm = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatório?", "Atenção",JOptionPane.YES_NO_OPTION );
      if (confirm== JOptionPane.YES_OPTION){
          InputStream caminhoRelatorio =this.getClass().getClassLoader().getResourceAsStream("relatorios/Relatório de Consultas.jasper");
           JasperPrint jasperPrint= null;
          
          try {
              jasperPrint = JasperFillManager.fillReport(caminhoRelatorio, null, con);
              
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao Gerar Relatório!\n"+ex);
          }
          JasperViewer view = new JasperViewer (jasperPrint, false);
          view.setVisible(true);
          
      }
    }//GEN-LAST:event_jMenuItemRelConsultasActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroRN;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonAgendaPacientes;
    private javax.swing.JButton jButtonAgendamento;
    private javax.swing.JButton jButtonCadEnfermeiro;
    private javax.swing.JButton jButtonCadMed;
    private javax.swing.JButton jButtonCadPaciente;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonExames;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMedicamento;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAgendamentoConsulta;
    private javax.swing.JLabel jLabelBorda;
    private javax.swing.JLabel jLabelBordaDataHora;
    private javax.swing.JLabel jLabelBuscaExames;
    private javax.swing.JLabel jLabelCadastroEnfermeiros;
    private javax.swing.JLabel jLabelCadastroMedicos;
    private javax.swing.JLabel jLabelCadastroPacientes;
    private javax.swing.JLabel jLabelCadastroUsuarios;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLupa1;
    private javax.swing.JLabel jLabelLupa3;
    private javax.swing.JLabel jLabelMedicacao;
    private javax.swing.JLabel jLabelPlanodeFundo;
    private javax.swing.JLabel jLabelPlus;
    private javax.swing.JLabel jLabelPlus10;
    private javax.swing.JLabel jLabelPlus2;
    private javax.swing.JLabel jLabelPlus3;
    private javax.swing.JLabel jLabelPlus4;
    private javax.swing.JLabel jLabelPlus5;
    private javax.swing.JLabel jLabelPlus6;
    private javax.swing.JLabel jLabelPlus8;
    private javax.swing.JLabel jLabelPlus9;
    private javax.swing.JLabel jLabelProcedimentos;
    private javax.swing.JLabel jLabelRX;
    private javax.swing.JLabel jLabelRadiotivo;
    private javax.swing.JLabel jLabelResultadoExames;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAgendaPacientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadMédicos;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemAgendaPacientes;
    private javax.swing.JMenuItem jMenuItemAgendarConsulta;
    private javax.swing.JMenuItem jMenuItemCadEnfermeiros;
    private javax.swing.JMenuItem jMenuItemCadPacientes;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemRelConsultas;
    private javax.swing.JMenuItem jMenuItemRelEnfermeiros;
    private javax.swing.JMenuItem jMenuItemRelMédicos;
    private javax.swing.JMenuItem jMenuItemRelPacientes;
    private javax.swing.JMenuItem jMenuItemRelUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void EXIT_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    class hora implements ActionListener {
    @Override   
    public void actionPerformed (ActionEvent e){
    Calendar now = Calendar.getInstance();    
    jLabelHora.setText(String.format("%1$tH:%1$tM", now));
}

    }
}
